require("focus").setup({
  enable = true,
  autoresize = true,
  hybridnumber = true,
  signcolumn = true,
  treewidth = 30,
  width = vim.api.nvim_get_option("textwidth") + 10,
  height = 40,
  minwidth = 10,
  minheight = 10,
  absolutenumber_unfocussed = true,
  colorcolumn = { enable = true, width = vim.api.nvim_get_option("textwidth") },
  bufnew = true,
  winhighlight = true,
  excluded_filetypes = {
    "NeogitCommitMessage",
    "NeogitStatus",
    "Outline",
    "dap-repl",
    "dapui_breakpoints",
    "dapui_console",
    "dapui_scopes",
    "dapui_stacks",
    "dapui_watches",
    "dashboard",
    "gina-commit",
    "gina-status",
    "help",
    "minimap",
    "qf",
    "toggleterm",
    "lspsagaoutline",
  },
  compatible_filetrees = { "nvimtree", "nerdtree", "chadtree", "fern" },
  -- Covered in core/filetype.vim
  cursorline = false,
  cursorcolumn = false,
})

vim.cmd("hi link UnfocusedWindow TabLine")
vim.cmd("hi link FocusedWindow VisualNOS")
